pipeline:
  build:
    image: python:2.7
    commands:
      - pip install -r test_requirements.txt
      - scripts/ci/test.sh

  notify:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/drone-plugin-slack
    channel: infra-salon
    secrets: [ slack_webhook ]
    when:
      event: [ push ]
      branch: master
      status: [ success, failure ]

  testspace:
    image: s2technologies/testspace-client
    pull: true
    commands:
      - testspace config url 4e2932be8e9326d29441f932f0bdc52cd9a66ac5@reddit.testspace.com
    #  - testspace TEST*.xml
    #secrets: [ testspace_token ]
    when:
      status: [ failure, success ]

secrets:
  slack_webhook:
    driver: vault
    driver_opts:
      path: secret/drone/common/slack_webhook
