branches:
    only:
        - master
        - add_testspace_support

sudo: required
dist: trusty
group: deprecated-2017Q2

language: python
python:
    - "2.7"

virtualenv:
    system_site_packages: true

before_install:
    - mkdir -p $HOME/bin
    - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
    - testspace config url reddit.testspace.com
    - sudo add-apt-repository -y ppa:reddit/ppa
    - sudo apt-get update -q
    - >
        sudo apt-get install -y \
            make \
            pylint \
            python \
            python3 \
            python3-coverage \
            python3-cqlmapper \
            python3-nose \
            python3-pip\
            python3-setuptools \
            python-coverage \
            python-mock \
            python-nose \
            python-pip \
            python-setuptools
    - sudo easy_install pip
    - sudo pip install -r test_requirements.txt

script:
    - nosetests -v
    - /usr/local/bin/flake8 --exit-zero rollingpin/
	- pylint --errors-only rollingpin/

after_script:
    - testspace static_analysis.log{lint} [py-${TRAVIS_PYTHON_VERSION}]nosetests.xml{.} build/coverage/coverage.xml
